Add missing cassert header
Fix build issue `error: ‘assert’ was not declared in this scope`
due to missing header "cassert" in the lidar_scan_impl.h or any included header